apiVersion: v1
kind: Secret
metadata:
  name: Jury_dagster
type: Opaque
stringData:
  SUPABASE_URL: "https://xumpzsmiyrweuaiswfep.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bXB6c21peXJ3ZXVhaXN3ZmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDcxNzEsImV4cCI6MjA1OTkyMzE3MX0.E__ed0bEJDjPJfSBoh61d0FSFt-1J6RdMhmHXeoboVI"
  MEILISEARCH_HOST: "https://meilisearch.dealwallet.com"  
  MEILISEARCH_KEY: "diNupMWTaJtR1pluZfoNzA=="
  MEILISEARCH_INDEX_NAME: "jury_index"
