name: dagster
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: csagent369
          password: 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
          logout: false
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/dealwallet1/${{ github.event.repository.name }}:latest
