name: Jury_dagster
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Ashwin1368
          password: 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
          logout: false
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/Jury_dagster/${{ github.event.repository.name }}:latest
